### 标量

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

### 向量->矩阵->更多维

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

In [6]:
# 创建矩阵
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
# 对称矩阵 B == B.T
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
print(B)
print(B == B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [12]:
# 就像向量是标量的推广，矩阵是向量的推广一样，可以构建具有更多轴的数据结构
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 张量

In [29]:
# 相加
A = torch.arange(12,dtype=torch.float32).reshape(3,4)
B = A.clone() # 通过分配新内存，将A的副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]))

In [14]:
# 哈达玛积 (按元素相乘)
A,B,A*B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]]))

In [16]:
# 张量和标量相乘
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a + X, (a*X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [64]:
# 计算元素的和
# 不论什么形状的张量，其元素的和永远是一个标量
A = torch.arange(20*2, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [65]:
# 指定张量的轴 进行 求和汇总
# tips：此处容易混淆
# 根据哪个维度求和，得到的结果就是将原shape中求和维度去掉后 剩下的维度
# 如shape:[2,5,4]，根据axis=0,2求和，得到shape:[5]

print(A)

A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0, A_sum_axis0.shape)

A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1, A_sum_axis1.shape)

A_sum_axis2 = A.sum(axis=2)
print(A_sum_axis2, A_sum_axis2.shape)

A_sum_axis01 = A.sum(axis=[0,1])
print(A_sum_axis01, A_sum_axis01.shape)

A_sum_axis02 = A.sum(axis=[0,2])
print(A_sum_axis02, A_sum_axis02.shape)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]]) torch.Size([5, 4])
tensor([[ 40.,  45.,  50.,  55.],
        [140., 145., 150., 155.]]) torch.Size([2, 4])
tensor([[  6.,  22.,  38.,  54.,  70.],
        [ 86., 102., 118., 134., 150.]]) torch.Size([2, 5])
tensor([180., 190., 200., 210.]) torch.Size([4])
tensor([ 92., 124., 156., 188., 220.]) torch.Size([5])


In [40]:
# 求平均值（可按维度）
print(A)

print(A.mean(), A.sum()/A.numel(), A.shape)

print(A.mean(axis=0), A.sum(axis=0)/A.shape[0])

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor(19.5000) tensor(19.5000) torch.Size([2, 5, 4])
tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]]) tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])


In [45]:
# 计算总和或均值时保持轴数不变
# keepdims即是保持原来的轴数不变，将指定的轴数变为1
# 如shape[2,5,4],根据轴数axis=1求和，则得到维度数目依然为3，维度为[2,1,4]

sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [47]:
# 通过广播A除以sum_A
print(A, sum_A)
A / sum_A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]]) tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])


tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [49]:
# 某个轴的累积求和
print(A)
A.cumsum(axis=0)


tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])


tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [53]:
# 点积：是标量；表示相同位置上的元素相乘 再求和
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

# 等价于sum(x*y)
torch.sum(x*y)

tensor(6.)

In [58]:
# 矩阵*向量
x = torch.arange(4, dtype=torch.float32)
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
print(A, A.shape)
print(x, x.shape)
torch.mv(A, x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) torch.Size([5, 4])
tensor([0., 1., 2., 3.]) torch.Size([4])


tensor([ 14.,  38.,  62.,  86., 110.])

In [59]:
# 矩阵*矩阵
B = torch.ones(4, 3)
print(A.shape, B.shape)
torch.mm(A, B)

torch.Size([5, 4]) torch.Size([4, 3])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [62]:
# 范数：向量或矩阵的长度

# L2范数：向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u) # 标量

# L1范数：向量元素的绝对值之和
torch.abs(u).sum()

# 矩阵的F范数：矩阵元素的平方和的平方根
A = torch.ones((4, 9))
torch.norm(A)

tensor(6.)

### 轴数详解

In [70]:
import torch

a = torch.ones((2,5,4))
a, a.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 5, 4]))

In [67]:
# shape为空，表示为标量
a.sum().shape

torch.Size([])

In [69]:
b = a.sum(axis=1)
b, b.shape


(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([2, 4]))

In [72]:
# keepdims 保留维度数目，将axis指定的维度值变为1
c = a.sum(axis=1, keepdims=True)
c, c.shape

(tensor([[[5., 5., 5., 5.]],
 
         [[5., 5., 5., 5.]]]),
 torch.Size([2, 1, 4]))

## QA

In [73]:
# Q:torch不区分行向量和列向量吗？
# A:torch中如果是一维向量的话 一定是行向量；如果要区分行列，可以用矩阵表示

In [74]:
# Q:张量的概念 机器学习里和数学中 有哪些区别？
# A:机器学习中的张量可以理解成数组，和数学中的张量不是一个概念